FROM vllm/vllm-openai:v0.21.0-cu129

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        fonts-noto-core \
        fonts-noto-cjk \
        fontconfig \
        libgl1 \
        libglib2.0-0 \
        curl && \
    fc-cache -fv && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install -U \
    'mineru[core]==3.4.5' \
    --break-system-packages && \
    python3 -m pip cache purge

ENV MINERU_MODEL_SOURCE=local

ENTRYPOINT ["/bin/bash", "-c", "exec \"$@\"", "--"]