[mypy]
python_version = 3.11
ignore_missing_imports = True
warn_unused_configs = True
warn_redundant_casts = True
no_implicit_optional = True
check_untyped_defs = False
exclude = (^alembic/|^tests/)

[mypy-tests.*]
ignore_errors = True
